def rot_13(string)
   string.tr("A-Za-z", "N-ZA-Mn-za-m")
end

def rot_13_tr(string)
   string.tr("A-Za-z", "N-ZA-Mn-za-m")
end

def rot_13_hash(string)
   hash = {
      'A'=> 'N',
      'B'=> 'O',
      'C'=> 'P',
      'D'=> 'Q',
      'E'=> 'R',
      'F'=> 'S',
      'G'=> 'T',
      'H'=> 'U',
      'I'=> 'V',
      'J'=> 'W',
      'K'=> 'X',
      'L'=> 'Y',
      'M'=> 'Z',
      'N'=> 'A',
      'O'=> 'B',
      'P'=> 'C',
      'Q'=> 'D',
      'R'=> 'E',
      'S'=> 'F',
      'T'=> 'G',
      'U'=> 'H',
      'V'=> 'I',
      'W'=> 'J',
      'X'=> 'K',
      'Y'=> 'L',
      'Z'=> 'M',
      'a'=> 'n',
      'b'=> 'o',
      'c'=> 'p',
      'd'=> 'q',
      'e'=> 'r',
      'f'=> 's',
      'g'=> 't',
      'h'=> 'u',
      'i'=> 'v',
      'j'=> 'w',
      'k'=> 'x',
      'l'=> 'y',
      'm'=> 'z',
      'n'=> 'a',
      'o'=> 'b',
      'p'=> 'c',
      'q'=> 'd',
      'r'=> 'e',
      's'=> 'f',
      't'=> 'g',
      'u'=> 'h',
      'v'=> 'i',
      'w'=> 'j',
      'x'=> 'k',
      'y'=> 'l',
      'z'=> 'm',
   }
   string.each_char.reduce('') {|acum, c| acum + (hash[c] ? hash[c] : c)}
end

def rot_13_gsub(string)
   hash = {
      'A'=> 'N',
      'B'=> 'O',
      'C'=> 'P',
      'D'=> 'Q',
      'E'=> 'R',
      'F'=> 'S',
      'G'=> 'T',
      'H'=> 'U',
      'I'=> 'V',
      'J'=> 'W',
      'K'=> 'X',
      'L'=> 'Y',
      'M'=> 'Z',
      'N'=> 'A',
      'O'=> 'B',
      'P'=> 'C',
      'Q'=> 'D',
      'R'=> 'E',
      'S'=> 'F',
      'T'=> 'G',
      'U'=> 'H',
      'V'=> 'I',
      'W'=> 'J',
      'X'=> 'K',
      'Y'=> 'L',
      'Z'=> 'M',
      'a'=> 'n',
      'b'=> 'o',
      'c'=> 'p',
      'd'=> 'q',
      'e'=> 'r',
      'f'=> 's',
      'g'=> 't',
      'h'=> 'u',
      'i'=> 'v',
      'j'=> 'w',
      'k'=> 'x',
      'l'=> 'y',
      'm'=> 'z',
      'n'=> 'a',
      'o'=> 'b',
      'p'=> 'c',
      'q'=> 'd',
      'r'=> 'e',
      's'=> 'f',
      't'=> 'g',
      'u'=> 'h',
      'v'=> 'i',
      'w'=> 'j',
      'x'=> 'k',
      'y'=> 'l',
      'z'=> 'm',
   }
   string.gsub(/[A-z]/, hash)
end

